---
title: "Assignment 5 Isochrones"
author: "Mary Geschwindt"
date: "10/2/2020"
output: 
  html_document:
    theme: paper
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following is a test of Assignment 4 based on the tutorial.

```{r message=false}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
```

```{r}
CPL_libraries <- st_read(
  "https://data.cambridgema.gov/api/geospatial/kn2z-b6eg?method=export&format=KML")
```

```{r}
opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_xml(file = 'OTP/graphs/default/cambridge_streets.osm')
```

```{r}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

cambridge_street_features <- opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

cambridge_streets <- cambridge_street_features$osm_lines %>%
  st_transform(crs = MA_state_plane)
```

```{r}
ggplot(cambridge_streets) +
  geom_sf() +
  theme_map()
```

```{r}
path_otp <- otp_dl_jar("OTP")
```

```{r message=FALSE, results='hide'}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```

```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)
```

```{r}
# Connect to opentripplanner
otpcon <- otp_connect()
```

```{r}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CPL_libraries, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "walk")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CPL_libraries, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_5min_drive, iso_5min_walk)

otp_stop()
```

```{r}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CPL_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

```{r}
ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "cartolight", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CPL_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

```{r}
ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "stamenwatercolor", 
                      progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CPL_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_discrete(name = "Area that is reachable within 5 minutes",
                      labels = c("By car", "By foot"),
                      type = c("gray", "black")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

```{r}
ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "stamenbw", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CPL_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

```{r}
ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "hotstyle", 
                      progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CPL_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_discrete(name = "Area that is reachable within 5 minutes",
                      labels = c("By car", "By foot"),
                      type = c("gray", "black")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

```{r}
ggplot(iso_all_modes) +
  geom_sf(data = cambridge_streets, color = "gray") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CPL_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() 
```

## Calculating and Comparing Isochrones

```{r}
iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a public library\n(square km)",
            breaks = breaks <- seq(10000, 130000, by = 20000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a public library\n(square km)",
            breaks = breaks <- seq(0, 700000, by = 100000),
            labels = breaks / 1000000) +
  theme_bw()
```
